const ARTICLE_STATES = {
  DRAFT: 'DRAFT',
  IN_REVIEW: 'IN_REVIEW',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  REWORK: 'REWORK',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
}

export { ARTICLE_STATES }
