const ARTICLE_STATES = {
  DRAFT: 'DRAFT',
  IN_REVIEW: 'IN_REVIEW',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  REWORK: 'REWORK',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
}

const ARTICLE_ERRORS = {
  ARTICLE_NOT_FOUND: 'ARTICLE_NOT_FOUND',
  INVALID_ACTION: 'INVALID_ACTION',
  INVALID_PUBLICATION_DATE: 'INVALID_PUBLICATION_DATE',
}

export { ARTICLE_STATES, ARTICLE_ERRORS }
