import S from 'fluent-json-schema'
import { getStates } from '../lib/common.js'

export function sCreateArticle() {
  return S.object()
    .additionalProperties(false)
    .prop('title', S.string().minLength(3).maxLength(200))
    .description('Article title.')
    .required()
    .prop('text', S.string().minLength(3))
    .description('Article text.')
    .prop('description', S.string().minLength(3).maxLength(500))
    .description('Article description.')
    .prop('categoryId', S.string().format('uuid'))
    .description('Article category id.')
    .required()
}

export function sArticleResponse() {
  return S.object()
    .description('Article.')
    .additionalProperties(false)
    .prop('id', S.string().format('uuid'))
    .description('Article id.')
    .prop('title', S.string().minLength(3).maxLength(200))
    .description('Article title.')
    .required()
    .prop('text', S.string().minLength(3))
    .description('Article text.')
    .prop('category', S.string().format('uuid'))
    .description('Article category.')
    .required()
    .prop('status', S.string().enum(getStates()))
    .description('Article status.')
    .required()
    .prop('author', S.string())
    .description('Article author.')
    .required()
    .prop('createdAt', S.string())
    .description('Article creation date.')
    .required()
    .prop('publishedAt', S.string())
    .description('Article publication date.')
    .required()
}

export function sArticleList() {
  return S.object()
    .additionalProperties(false)
    .prop('id', S.string().format('uuid'))
    .description('Article id.')
    .prop('title', S.string().minLength(3).maxLength(200))
    .description('Article title.')
    .required()
    .prop('author', S.string())
    .description('Article author.')
    .required()
    .prop('status', S.string().enum(getStates()))
    .description('Article status.')
    .required()
    .prop('publishedAt', S.string().format('date-time'))
    .description('Article publish date.')
    .required()
}
