version: '3.5'
##TODO creare docker-compose separato per tools
services:
  postgres:
    container_name: postgres-pd
    image: postgres:12.4
    restart: always
    ports:
      - 5432:5432
    networks:
      - database-pd
    volumes:
      - postgres-pd:/var/lib/postgresql/data
      - ./conf/postgres/1-create-user-and-db.sh:/docker-entrypoint-initdb.d/1-create-user-and-db.sh
      - ./conf/postgres/2-insert-mock-data.sh:/docker-entrypoint-initdb.d/2-insert-mock-data.sh
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Rome"
      PGTZ: "Europe/Rome"

  redis:
    container_name: redis-pd
    image: redis-pd
    restart: always
    ports:
      - 6379:6379
    networks: 
      - database-pd
    volumes:
      - redis-pd:/data

networks:
  database-pd:
    name: database-pd

volumes:
  postgres-pd:
    name: postgres-pd
  redis-pd:
    name: redis-pd