
CREATE TABLE IF NOT EXISTS regions (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS provinces (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(50) UNIQUE NOT NULL,
    code CHAR(2) UNIQUE NOT NULL,
    id_region INT NOT NULL,
    CONSTRAINT fk_id_region FOREIGN KEY(id_region) REFERENCES regions(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    user_name VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    type VARCHAR(10) NOT NULL CHECK (type in ('backoffice', 'site')),
    password VARCHAR(60) NOT NULL,
    birth_date timestamp CHECK (birth_date > '1900-01-01'),
    joined_date timestamp CHECK (joined_date > birth_date),
    sex VARCHAR(10) CHECK (sex in ('male', 'female', 'other')),
    bio VARCHAR (500),
    owner_id INT NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT false,
    is_deleted BOOLEAN NOT NULL DEFAULT false,
    created_at timestamp DEFAULT NOW(),
    updated_at timestamp DEFAULT NOW(),
    updated_by INT,
    deleted_by INT,
    last_access timestamp,
    id_region INT NOT NULL,
    id_province INT NOT NULL,
    CONSTRAINT fk_owner_id FOREIGN KEY(owner_id) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_updated_by FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_deleted_by FOREIGN KEY(deleted_by) REFERENCES users(id) ON DELETE NO ACTION,
    CONSTRAINT fk_id_region FOREIGN KEY(id_region) REFERENCES regions(id) ON DELETE NO ACTION,
    CONSTRAINT fk_id_province FOREIGN KEY(id_province) REFERENCES provinces(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INT NOT NULL,
    email VARCHAR(50) NOT NULL,
    user_agent TEXT NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    expired_at timestamp NOT NULL,
    last_active timestamp NOT NULL DEFAULT NOW(),
    is_valid BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS reset_links (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id INT NOT NULL,
    token VARCHAR(60) NOT NULL,
    already_used BOOLEAN NOT NULL DEFAULT false,
    expired_at timestamp NOT NULL,
    created_at timestamp DEFAULT NOW(),
    CONSTRAINT fk_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE NO ACTION
);