INSERT INTO categories (name, type) VALUES
('Affari Esteri', 'ACTIVITY'),
('Agricoltura', 'ACTIVITY'),
('Ambiente', 'ACTIVITY'),
('Cultura', 'ACTIVITY'),
('Economia', 'ACTIVITY'),
('Giustizia', 'ACTIVITY'),
('Immigrazione', 'ACTIVITY'),
('Istruzione', 'ACTIVITY'),
('Lavoro', 'ACTIVITY'),
('Mezzo Giorno', 'ACTIVITY'),
('Pari opportunità', 'ACTIVITY'),
('Pensioni', 'ACTIVITY'),
('Politiche Regionali', 'ACTIVITY'),
('Sanità', 'ACTIVITY'),
('Sicurezza', 'ACTIVITY'),
('Tecnologia e Innovazione', 'ACTIVITY'),
('Trasporti', 'ACTIVITY'),
('Turismo', 'ACTIVITY'),
('Welfare', 'ACTIVITY');


INSERT INTO categories (name, type) VALUES
('Notizie recenti', 'ARTICLE'),
('Ultime dalla politica', 'ARTICLE'),
('Cronaca politica', 'ARTICLE'),
('Analisi e commenti', 'ARTICLE'),
('Dossier speciali', 'ARTICLE'),
('Inchieste', 'ARTICLE'),
('Guida alle istituzioni', 'ARTICLE'),
('Processi legislativi', 'ARTICLE'),
('Elezioni e sistema elettorale', 'ARTICLE'),
('Politici', 'ARTICLE'),
('Esperti', 'ARTICLE'),
('Cittadini', 'ARTICLE'),
('Editoriali', 'ARTICLE'),
('Lettere al direttore', 'ARTICLE'),
('Dibattiti', 'ARTICLE'),
('Eventi storici', 'ARTICLE'),
('Biografie di figure politiche', 'ARTICLE'),
('Contesto storico delle politiche attuali', 'ARTICLE'),
('Scenari politici', 'ARTICLE'),
('Proiezioni e sondaggi', 'ARTICLE'),
('Tendenze emergenti', 'ARTICLE'),
('Impatto sociale delle politiche', 'ARTICLE'),
('Movimenti civili e proteste', 'ARTICLE'),
('Questioni di giustizia sociale', 'ARTICLE'),
('E-government e digitalizzazione', 'ARTICLE'),
('Cybersecurity', 'ARTICLE'),
('Influenza dei social media sulla politica', 'ARTICLE'),
('Calendario degli eventi', 'ARTICLE'),
('Resoconti di conferenze e summit', 'ARTICLE'),
('Appuntamenti importanti', 'ARTICLE');