const STATES = {
  DRAFT: 'DRAFT',
  IN_REVIEW: 'IN_REVIEW',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  REWORK: 'REWORK',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
}

const CATEGORY_TYPES = {
  ARTICLE: 'ARTICLE',
  ACTIVITY: 'ACTIVITY',
}

const FILE_TARGETS = {
  TEXT: 'TEXT',
  DESCRIPTION: 'DESCRIPTION',
}
export function getFileTargets() {
  return Object.values(FILE_TARGETS)
}

const ARTICLE_STATES = STATES
const ACTIVITY_STATES = STATES

const POLITICIAN_TYPE = {
  SENATOR: 'SENATOR',
  DEPUTY: 'DEPUTY',
}

export {
  STATES,
  ARTICLE_STATES,
  ACTIVITY_STATES,
  CATEGORY_TYPES,
  POLITICIAN_TYPE,
}
