const STATES = {
  DRAFT: 'DRAFT',
  IN_REVIEW: 'IN_REVIEW',
  READY: 'READY',
  PUBLISHED: 'PUBLISHED',
  REWORK: 'REWORK',
  ARCHIVED: 'ARCHIVED',
  DELETED: 'DELETED',
}

const CATEGORY_TYPES = {
  ARTICLE: 'ARTICLE',
  ACTIVITY: 'ACTIVITY',
}

const FILE_TARGETS = {
  TEXT: 'TEXT',
  DESCRIPTION: 'DESCRIPTION',
}

const ARTICLE_STATES = STATES
const ACTIVITY_STATES = STATES

export { STATES, ARTICLE_STATES, ACTIVITY_STATES, CATEGORY_TYPES }

export function getFileTargets() {
  return Object.values(FILE_TARGETS)
}
