#!/bin/bash

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER politicalDilemma with password 'password';
    CREATE DATABASE politicalDilemma WITH OWNER politicalDilemma;

    \connect politicalDilemma;

    CREATE TABLE IF NOT EXISTS roles (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        type VARCHAR(50) NOT NULL CHECK (type = 'admin' OR type = 'member'),
        description TEXT
    );

    CREATE TABLE IF NOT EXISTS users (
        id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        firstName VARCHAR(50),
        lastName VARCHAR(50),
        username VARCHAR(50) UNIQUE NOT NULL,
        email VARCHAR(50) UNIQUE NOT NULL,
        password VARCHAR (128) NOT NULL,
        bio TEXT,
        isBlocked BOOLEAN DEFAULT false,
        createdAt timestamp DEFAULT NOW(),
        updatedAt timestamp,
        roleId INT NOT NULL,
        CONSTRAINT fk_role FOREIGN KEY(roleId) REFERENCES roles(id) ON DELETE NO ACTION
    );

    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO politicalDilemma;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO politicalDilemma;
EOSQL