version: '3.5'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - postgres-pd
    restart: always
    ports:
      - 8000:80
    networks:
      - database
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    depends_on:
      - redis-pd
    restart: always
    ports:
      - 8081:8081
    networks:
      - database
    environment:
      REDIS_HOSTS: local:redis:6379

  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

networks:
  database:
    name: database

volumes:
  portainer:
    name: portainer
  pgadmin:
    name: pgamin
